config/routes.rb
TokenApp::Application.routes.draw do
  get "home/index"

#  devise_for :users, :controllers => { :sessions => "users/sessions" }
  
  devise_for :users, :controllers => { :sessions => "sessions" }

  devise_scope :user do
    resources :sessions, :only => [:create, :destroy]
  end
  
  resources :token_authentications, :only => [:create, :destroy]

  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable
         
  before_save :ensure_authentication_token     

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create
    respond_to do |format|
      format.html { super }
      format.xml {
        warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#new")
        render :status => 200, :xml => { :session => { :error => "Success", :auth_token => current_user.authentication_token }}
      }
 
      format.json {
        warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#new")
        render :status => 200, :json => { :session => { :error => "Success", :auth_token => current_user.authentication_token } }
      }
    end
  end
 
  def destroy
    respond_to do |format|
      format.html { super }
      format.xml {
        warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#new")
        current_user.authentication_token = nil
        render :xml => {}.to_xml, :status => :ok
      }
 
      format.json {
        warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#new")
        current_user.authentication_token = nil
        render :json => {}.to_json, :status => :ok
      }   
    end    
  end
end

app/controllers/token_authentications_controller.rb
class TokenAuthenticationsController < ApplicationController

  before_filter :authenticate_user!
 
  def create
    @user = current_user
    @user.reset_authentication_token!
    redirect_to edit_user_registration_path(@user)
  end
 
  def destroy
    @user = current_user
    @user.authentication_token = nil
    @user.save
    redirect_to edit_user_registration_path(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/token_authentications_helper.rb
module TokenAuthenticationsHelper
end

app/views/home/index.html.haml
%h1 Welcome Home
%p Welcome to the landing page

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TokenApp
    /[if lt IE 8]
    = stylesheet_link_tag 'ie.css', :media => 'screen, projection'    
    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'print.css', :media => 'print'
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body.bp.two-col
    #container
      %header       
        %nav
          %ul.nav-menu
            - if user_signed_in?
              %li= link_to "Home", home_index_path
              %li= link_to "Account", edit_user_registration_path(@user)
              %li= link_to "Logout", destroy_user_session_path, :method => :delete
            - else
              %li= link_to "Signup", new_user_registration_path
              %li= link_to "Login", new_user_session_path
      - flash.each do |key, value|
        %div{:class => "flash #{key}"}= value                     
      #content    
        = yield
      %footer
    = debug(params) if Rails.env.development?